### PR TITLE
Properties

### PR DESCRIPTION
**Pull request by paul-aigue**
Wrap Geometry in Feature object to handle the properties dictionary from GEOJson feature.

This will answer to #53

### CODE REVIEW

**Comment by paul-aigue** [comment]
@vfn is this change looks good to you ? It's a model improvement with the GEOJson Features concept and let us get properties dictionary.

**Comment by vfn** [comment]
Merged. Thanks, @paul-aigue!

**Comment by paul-aigue** [comment]
@vfn is this version will be released in Cocoapod ?

**Comment by vfn** [comment]
@paul-aigue new pod released as 2.1.0. Thanks!

**Pull request merged**
