### PR TITLE
Carthage fix

### PR DESCRIPTION
**Pull request by madhavajay**
Okay so this time its much better.
This relies on the PR over at geos:
https://github.com/GEOSwift/geos/pull/5

1) I added a Cartfile which uses the above geos Carthage dependency
2) I added the xcconfig files to the Repo that way they dont need to be removed from the project
3) I removed the test target because of this error:
```
Carthage/Checkouts/GEOSwift/GEOSwiftTests/QuickLookTests.swift:13:18: error: module 'GEOSwift' was not compiled for testing
@testable import GEOSwift
```
We shouldn't compile the library for Production with @testable enabled so this should be done as part of an App Target or its own Test Target, but not attached to the Framework directly.

4) I added a Preprocessing Target step which Copies the geos.framework from Carthage to a folder and filename that the Cocoapods setup is expecting and it works. This is skipped if the CARTHAGE=YES environment variable isn't set.

It seems to work great! :)

Also, it should be pretty easy to add the additional tvOS and macOS targets to this library if you wish now that they are part of the geos dependency.

Thoughts?

### CODE REVIEW

**Comment by madhavajay** [comment]
Okay so I have the tests running again but two are failing:
```
QuickLookTests
[01:41:44]: ▸ ✗ testDrawGeometryCollection, XCTAssertEqual failed: ("Optional(6088 bytes)") is not equal to ("Optional(6098 bytes)")
[01:41:44]: ▸ ✗ testDrawWaypoint, XCTAssertEqual failed: ("Optional(4514 bytes)") is not equal to ("Optional(4491 bytes)")
```

Is it possible something has changed in QuickLook?

**Comment by macdrevx** [comment]
I'd check to make sure the tests are still running on "iPhone XS" simulator. The snapshot tests are simulator-dependent for some reason.

**Comment by madhavajay** [comment]
@macdrevx 😅Looks like it worked. 😎

**Comment by madhavajay** [comment]
@macdrevx Anything preventing this from being merged?

**Comment by macdrevx** [comment]
I just need some time to review it. Sorry for the delay.

**Comment by macdrevx** [comment]
@madhavajay I pushed a branch https://github.com/GEOSwift/GEOSwift/tree/carthage with a different approach. Can you try it out and let me know if it works for you?

Instead of working around CocoaPods, I switched the project to use Carthage for development purposes. CocoaPods is still available for consumers. This seems simpler to me.

The only problem left that I'm aware of is that I get an error when I try running the playground.

```
error: Couldn't lookup symbols:
  type metadata accessor for GEOSwift.MultiPolygon
  type metadata accessor for GEOSwift.Feature
  type metadata accessor for GEOSwift.Polygon
  type metadata accessor for GEOSwift.Envelope
  GEOSwift.Geometry.convexHull() -> Swift.Optional<GEOSwift.Polygon>
  GEOSwift.Geometry.difference(GEOSwift.Geometry) -> Swift.Optional<GEOSwift.Geometry>
  GEOSwift.Geometry.intersection(GEOSwift.Geometry) -> Swift.Optional<GEOSwift.Geometry>
  GEOSwift.Geometry.pointOnSurface() -> Swift.Optional<GEOSwift.Waypoint>
  GEOSwift.Geometry.__allocating_init(WKT: Swift.String) -> Swift.Optional<GEOSwift.Geometry>
  GEOSwift.Geometry.union(GEOSwift.Geometry) -> Swift.Optional<GEOSwift.Geometry>
  GEOSwift.Geometry.buffer(width: Swift.Double) -> Swift.Optional<GEOSwift.Geometry>
  GEOSwift.Geometry.boundary() -> Swift.Optional<GEOSwift.Geometry>
  GEOSwift.Geometry.centroid() -> Swift.Optional<GEOSwift.Waypoint>
  GEOSwift.Geometry.envelope() -> Swift.Optional<GEOSwift.Envelope>
  GEOSwift.Geometry.mapShape() -> Swift.Optional<__C.MKShape>
  type metadata accessor for GEOSwift.Geometry
  type metadata accessor for GEOSwift.Waypoint
  static (extension in GEOSwift):Swift.Array<A where A == GEOSwift.Feature>.fromGeoJSON(Foundation.URL) throws -> Swift.Optional<Swift.Array<GEOSwift.Feature>>
```

Do you have any ideas on how to get it working again?

Regarding number 3 in your PR description: I saw that error too, but it was solved by a change to the scheme to prevent the tests from being compiled unless we're actually building for test.

scheme change

**Comment by madhavajay** [comment]
Yes, I think using Carthage is a nicer solution than the above hack but I wasn't sure you would want to overhaul the whole dependency management system.

I have added a PR which fixes the Playground issue.
https://github.com/GEOSwift/GEOSwift/pull/152

Let me know if you have any issues with it! :)

**Comment by macdrevx** [comment]
Closing this in favor of #153.

**Pull request closed without merging**
