### PR TITLE
Carthage

### PR DESCRIPTION
**Pull request by madhavajay**
Firstly for people who just want it to work I have uploaded a binary that Carthage can use:

Cartfile
```
github "madhavajay/GEOSwift" ~> 3.2.0
```

I also managed to almost get this to work as part of the original project.
To get Carthage to build this as a dependency I had to do the following:
- Removing Test Target during Framework build
- Test target requires code signing
- Remove missing xcconfigs which stop build, pod install fixes anyway
- Added Carthage path to Check Pods Manifest script
- If called from Carthage, simply run pod install to get dependency

This works except that the sub dependency geos inside the cocopod is not built yet.
I am pretty sure that can be fixed a few ways:
- Give the geos project its own xcodeproject file which builds the framework and add it as a Cartfile dependency to the main GEOSwift project
- Add a separate fork of geos with Carthage
- Find a way to trigger the geos build with cocoapods from the command line and add it to the CARTHAGE branch of the Check Pods Manifest script

Also @macdrevx another solution and probably a good idea anyway is for you to simply upload a zip file of the iOS framework when it's finished building to the release page. Carthage automatically grabs these if they exist.

### CODE REVIEW

**Comment by mmarkov-appolica** [comment]
I hope it will get merged soon

**Comment by madhavajay** [comment]
Could be a few causes of the error:
The test target was removed from the framework build so perhaps its worth adding a demo app rather than a playground which uses the iOS framework.

```
 xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES clean test | xcpretty -c;
--- xcodebuild: WARNING: Unable to open project file '/Users/travis/build/GEOSwift/GEOSwift/GEOSwift.playground' in workspace 'GEOSwift.xcworkspace'.
xcodebuild: error: Scheme GEOSwift is not currently configured for the test action.

The command "xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES clean test | xcpretty -c;" exited with 66.
```

**Comment by macdrevx** [comment]
Hi @madhavajay, thanks for the PR. I have some questions and requests:

* I like your suggestion to "Give the geos project its own xcodeproject file which builds the framework and add it as a Cartfile dependency to the main GEOSwift project". Can you open a PR for that here: https://github.com/GEOSwift/geos ?
* Can you please update the PR to not include the changes from the feature/swift5 branch?
* Can you also update the PR to merge into develop?
* I don't understand why it was necessary to remove the xcconfigs. Like you said, `pod install` re-adds them and you added `pod install` to the carthage build. Why not just leave the xcconfigs as they were?
* Instead of removing test target during framework build, would it work to simply remove the code signing requirement from the test target?

**Comment by madhavajay** [comment]
Hi @macdrevx Good questions:

I like your suggestion to "Give the geos project its own xcodeproject file which builds the framework and add it as a Cartfile dependency to the main GEOSwift project". Can you open a PR for that here: https://github.com/GEOSwift/geos ?
- Yes I will investigate this

Can you please update the PR to not include the changes from the feature/swift5 branch?
Can you also update the PR to merge into develop?
- Sure I can go back and make these changes to develop

I don't understand why it was necessary to remove the xcconfigs. Like you said, pod install re-adds them and you added pod install to the carthage build. Why not just leave the xcconfigs as they were?
- Yeah this is really annoying but the xcode project wont build if there are missing files. This means theres no chance to run a custom script to resolve the sub dependency issue.
- I cannot see a way around this as I cant see any way to do any "prehook" scripts with carthage either. I think this is a bit of a weakness of Cocoapods and Xcode that the committed code isnt in a runable state without manually running pod install first. However I found that if I remove these missing xcode config files the project would start to build and then the pod install hook could run and resolve the dependency. Unfortunately it seems that this then fails (probably xcode isnt picking up the new files), but will succeed on the next subsequent run.

Instead of removing test target during framework build, would it work to simply remove the code signing requirement from the test target?
- Unfortunately we can't the way Apple does things is the UI tests need to be deployed to the device and therefore count the same way an App does and require signing. Frameworks are exempt from this because it would make open source frameworks with CI and automated builds practically impossible if they needed to be signed to be built and shared.
- I believe the proper way people do this is they have:
1) Example App which has Tests and Framework embedded in it
2) UI Tests
3) Framework target in the same Xcode Project file
That way if you load it up you can run the Example app and play with it on your device or run the tests either in the simulator or on device, but Carthage will simply ignore all of these and build the framework target only when it is used as a dependency.

I think ultimately the biggest difficulty in using Carthage here is that you are using Cocoapods as the dependency for a Cocoapods framework so this kind of nested dependency becomes a bit of an issue.

I think perhaps the best solution here is to start with the geos project and get that into an xcode project which can be built with Cocoapods and Carthage and then see how integrating it into the parent GEOSwift project would work best.

If you want to install carthage and create a demo project and add GEOSwift to it you will see the issues. Its pretty easy to develop on you can just do the following:
1) Clone down GEOSwift
2) use a relative path in your carthage file e.g.:
git "/Users/example/GEOSwift" "test-branch"
3) When you run carthage update it will get the code from there
4) Run carthage update --verbose, when it fails check the logs
5) Go into Carthage/Checkouts/GEOSwift and open the xcode workspace
make changes until you can get it to build
6) Commit those changes to your relative path checkout
7) Remove Carthage folder and Run carthage update --verbose again

That might help understand and debug the issues.

Maybe it's worth looking at using SPM to manage the immediate geos dependency since it should be available on all systems, and then provide both Carthage and Cocoapods as well as SPM support to the GEOSwift project?

Thoughts?

**Comment by madhavajay** [comment]
@macdrevx Thinking about the UI test issue again, this really shouldnt be a problem:
https://github.com/fastlane/fastlane/issues/7622

Perhaps we just need to make sure the setting is set explicitly.

**Pull request closed without merging**
