### PR TITLE
added optionals to the SpatialAnalysis.swift file

### PR DESCRIPTION
**Pull request by jwilson85**

### CODE REVIEW

**Comment by jwilson85** [comment]
I dont know what this means. Is there a plan to accept this pull request?

**Comment by jwilson85** [comment]
It built locally. I'm not sure what travis-ci is doing.

**Comment by vfn** [comment]
@jwilson85 Travis uses the configs from the .travis.yml file.  It would be great if you could help fixing the build and maybe adding Xcode 9.3 support.

Cheers!

**Comment by jwilson85** [comment]
It built for me using xcode9.3. When I get home I’ll take a look into this yml file you speak of

**Comment by jwilson85** [comment]
So I looked at the YML file, it looks like a config for something. My guess is I would have to install Travis. From my experience with CI. It's probably best to solve this issue on the actual CI server. As there is often local configuration stuff. Also, I just have no experience with Travis. So I would spend hours just getting up to speed. Meanwhile, we have a breaking crash in our app that is stopping us from releasing. Is there any way you can help speed up this process.

**Comment by vfn** [comment]
@jwilson85, that's correct. The issue need to be resolved on Travis environment, and not on a local setup.

For the time being, you can setup your project to you your fork of the repo with the code from your PR. Look at the `Source` section https://guides.cocoapods.org/syntax/podfile.html#pod

It would be great if you could help getting the build fix in the near future.

**Comment by vfn** [comment]
@jwilson85 I have done some changes and fixed the build. I merged your changes and I'll be publishing a new pod version (`2.2.0`) soon.

**Pull request merged**
