### PR TITLE
Upgrade to Swift 5, etc

### PR DESCRIPTION
**Pull request by macdrevx**
@chris-bridj could you take a look to see whether these changes still work for you under SPM?

### CODE REVIEW

**Comment by macdrevx** [comment]
We have 2 failing snapshot tests (for the quicklook stuff). I'm out of time right now, but I'll look into it later this week.

**Comment by macdrevx** [comment]
Tests were failing b/c I updated a couple snapshot images that shouldn't have been updated. When running tests on Travis, we use iPhone XS sim, but I was using iPhone XR locally which rendered things slightly differently. I reverted my changes to the snapshot images, which will hopefully fix the build.

**Comment by macdrevx** [comment]
@chris-bridj I did a quick test with macOS/brew/spm and saw build+test pass, so I’m going to proceed with release once I get a review. Let me know if you run into any issues though.

**Comment by ccorn90** [comment]
@macdrevx Sorry for the slow response... I changed handles so everything from @chris-bridj is now going to @ccorn90.  I'll take a look in the next couple days, but if things build okay on macOS, then I think you should proceed!

Chris

**Pull request merged**
