### PR TITLE
properties dictionary added

### PR DESCRIPTION
**Pull request by cbarbera80**

### CODE REVIEW

**Comment by vfn** [comment]
@cbarbera80 could you add some context on what this PR adds/fixes, and please make sure the tests are passing.

**Comment by zhouhao27** [comment]
I think this is what I want. I'm able to get extra field from geoJson. Am I right?

**Comment by vfn** [comment]
@zhouhao27 It looks like it. Could you refactor this PR and make sure tests are added and passing?

**Comment by paul-aigue** [comment]
is this pull-request will be merge ?

**Comment by vfn** [comment]
@paul-aigue, would you like to take over and update this PR? It would be great to have this code moved to Swift 4 and possibly using the Decodable protocol.

**Comment by paul-aigue** [comment]
I did something similar for properties dict before using Swift 4 and Decodable. #57

**Comment by vfn** [comment]
Properties added on https://github.com/GEOSwift/GEOSwift/pull/57

**Pull request closed without merging**
