### PR TITLE
Add public init for Feature

### PR DESCRIPTION
**Pull request by sauvikated**
It will be really nice to be able to create an instance of `Feature`, adding values to it and substantially create a collection of them as `Features`.

### Scenario:

Suppose we have `[String]` of encoded polylines generated using `- (NSString *) encodedPath			
` on an instance of `GMSPath` **while recoding a transportation movement by a vehicle** . [Documentation](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_path#a9b5b3808fbdc30e21a4b9d53e70058f7).

So we can 

1. Iterate over the `[String]`, 
2. Decode each single encoded string
3. Create an instance of `LineString` from it
4. Add the `LineString` instance to the `geometries` of `Feature`
5. Add additional values for `properties` and `id`
6. Create a `Features` inserting every single `Feature`

### CODE REVIEW

**Comment by macdrevx** [comment]
@sauvikated, thanks for the PR. Can you update it to be based off of develop instead of master?

**Comment by sauvikated** [comment]
@macdrevx Done.

**Comment by macdrevx** [comment]
I rebased onto develop to get rid of those merge commits.

**Comment by macdrevx** [comment]
This will go out with the next release along with #153.

**Pull request merged**
