### PR TITLE
Create Geometry from GeoJSON string

### PR DESCRIPTION
**Pull request by rugheid**
I just added a simple utility function that converts a given string to data to be parsed by the GeoJSON parser.

### CODE REVIEW

**Comment by vfn** [comment]
Hi @rugheid, thanks for contributing!

Could you please do a minor refactor to your PR. Please push only the changes you have done to `GEOSwift/GeoJSON.swift` file, and could you add tests as well?

Thanks!

**Comment by rugheid** [comment]
Sorry for the late reply, but I cleaned up and added tests as requested.

**Comment by vfn** [comment]
@rugheid That's great!

I have made some changes and created a PR on your repo. once you merge it there, please update this PR and I'll merge it.

Thanks!

**Comment by oroom** [comment]
@vfn I recreated this PR as https://github.com/GEOSwift/GEOSwift/pull/77 with all your updates merged and fixed conflicts.

**Comment by vfn** [comment]
Merged via https://github.com/GEOSwift/GEOSwift/pull/77

**Pull request closed without merging**
